server:
  port: 6002
#EurekaServer配置
eureka:
  instance:
    hostname: eureka6002.com
  client:
    register-with-eureka: false #此EurekaServer不在注册到其他的注册中心
    fetch-registry: false       #不在从其他中心中心拉取服务器信息
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka #注册中心访问地址
